### ISSUE TITLE
After applying Pyxis, a namespace permission error occurred.

### ISSUE THREAD

**Issue by tym1062** [NVIDIA/enroot#61] opened 2021-02-24 19:07 UTC
**Environment:**
Baremetal 8xA100 
PRETTY_NAME="Oracle Linux Server 7.9"
Kernel:  5.4.17-2036.100.6.1.el7uek.x86_64
NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0
slurm-20.11.2-1.el7.x86_64

**Error:** 
After applying Pyxis, we did a job test. However, namespace permission error occurred. 
Problem state
$ srun --container-image=/nfs/cluster/pyxis_test/enroot_image/centos.sqsh grep PRETTY /etc/os-release
slurmstepd: error: pyxis: container start failed with error code: 1
slurmstepd: error: pyxis: printing contents of log file ...
slurmstepd: error: pyxis:     enroot-nsenter: failed to create user namespace: Permission denied
slurmstepd: error: pyxis: couldn't start container
slurmstepd: error: pyxis: if the image has an unusual entrypoint, try using --no-container-entrypoint
slurmstepd: error: spank: required plugin spank_pyxis.so: task_init() failed with rc=-1
slurmstepd: error: Failed to invoke spank plugin stack
srun: error: inst-foysz-vocal-drake: task 0: Exited with exit code 1
 
**Check the current settings**
```
$ ./enroot-check_*.run --verify
Kernel version:
Linux version 5.4.17-2036.100.6.1.el7uek.x86_64 (mockbuild@jenkins-172-17-0-2-980b5770-aa59-43ca-ab82-ac28f1d4376e) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.3) (GCC)) NVIDIA/pyxis#2 SMP Thu Oct 29 17:04:48 PDT 2020
Kernel configuration:
CONFIG_NAMESPACES                 : OK
CONFIG_USER_NS                    : OK
CONFIG_SECCOMP_FILTER             : OK
CONFIG_OVERLAY_FS                 : OK (module)
CONFIG_X86_VSYSCALL_EMULATION     : OK
CONFIG_VSYSCALL_EMULATE           : KO (required if glibc <= 2.13)
CONFIG_VSYSCALL_NATIVE            : KO (required if glibc <= 2.13)
 
Kernel command line:
 
vsyscall=native                   : KO (required if glibc <= 2.13)
vsyscall=emulate                  : KO (required if glibc <= 2.13)
 
Kernel parameters:
 
user.max_user_namespaces          : OK
user.max_mnt_namespaces           : OK
 
Extra packages:
 
nvidia-container-cli              : OK
```

**Kernel parameters updated and did a reboot.    After reboot:** 

```
[root@inst-foysz-vocal-drake ~]# sudo grubby --info /boot/vmlinuz-5.4.17-2036.100.6.1.el7uek.x86_64
index=1
kernel=/boot/vmlinuz-5.4.17-2036.100.6.1.el7uek.x86_64
args="ro crashkernel=auto LANG=en_US.UTF-8 console=tty0 console=ttyS0,9600 rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 rd.iscsi.bypass=1 rd.net.timeout.carrier=5 rd.net.timeout.dhcp=10 netroot=iscsi:169.254.0.2:::1:iqn.2015-02.oracle.boot:uefi iscsi_param=node.session.timeo.replacement_timeout=6000 net.ifnames=1 nvme_core.shutdown_timeout=10 ipmi_si.tryacpi=0 ipmi_si.trydmi=0 ipmi_si.trydefaults=0 libiscsi.debug_libiscsi_eh=1 loglevel=4 ip=dhcp nouveau.modeset=0 rd.driver.blacklist=nouveau namespace.unpriv_enable=1 user_namespace.enable=1"
root=UUID=a46bac1b-7608-4d7c-b8c6-a3abca37be9f
initrd=/boot/initramfs-5.4.17-2036.100.6.1.el7uek.x86_64.img
title=Oracle Linux Server 7.9, with Unbreakable Enterprise Kernel 5.4.17-2036.100.6.1.el7uek.x86_64
[root@inst-foysz-vocal-drake ~]#

```

**Investigation:**
I started looking at enroot source code and found bundle.sh which has logic to validate if the kernel parameters were set.   
https://github.com/NVIDIA/enroot/blob/master/src/bundle.sh#L145:L155
You will see it only checks for “centos7*|rhel7*“. ,  should this be updated to add Oracle Linux like this ?    centos7*|rhel7*|ol7”
 
On OCI cloud
```
source /etc/os-release 2> /dev/null; echo "${ID-}${VERSION_ID-}"
ol7.9
```
 
I did a sample “enroot” test like below and it worked fine with the default bundle.sh and with bundle.sh modified to include “ol7*”  and both times it worked.  

I ran this sample example.  This is standalone, so it helps to isolate enroot issue from slurm or slurm pyxis invoking enroot. 
 
_Usage example:_
```
# Import and start an Ubuntu image from DockerHub
$ enroot import docker://ubuntu
$ enroot create ubuntu.sqsh
$ enroot start ubuntu
```

I am not an enroot or pyxis expert,  but I am assuming,  since standalone enroot works,  the issue could be in how pyxis is configured to use enroot or pyxis follows a code path which is different from the above simple example.  

**How was pyxis installed and configured?**

Install

Since RPM package is not currently provided, for Oracle Linux the source installation was used. From Pyxis github, clone source and build. 

```
$ git clone https://github.com/NVIDIA/pyxis.git
$ cd pyxis
$ sudo make install
cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic -D_GNU_SOURCE cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic -D_GNU_SOURCE cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic -D_GNU_SOURCE cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic -D_GNU_SOURCE cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic -D_GNU_SOURCE cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic -D_GNU_SOURCE cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic -D_GNU_SOURCE cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic -D_GNU_SOURCE cc -shared -Wl,-znoexecstack -Wl,-zrelro -Wl,-znow -o spank_pyxis.so spank_pyxis.lds common.strip --strip-unneeded -R .comment spank_pyxis.so
install -d -m 755 /usr/local/lib/slurm
install -m 644 spank_pyxis.so /usr/local/lib/slurm
install -d -m 755 /usr/local/share/pyxis
echo 'required /usr/local/lib/slurm/spank_pyxis.so' | install -m 644 /dev/stdin /usr/local/
$ sudo mkdir /etc/slurm/plugstack.conf.d
$ ln -s /usr/local/share/pyxis/pyxis.conf /etc/slurm/plugstack.conf.d/pyxis.conf
# systemctl restart slurmd

```

Github's installation guide specifies the path of the spank_pyxis.so library built in /etc/slurm/plugstack.conf.d/pyxis.conf to recognize the Spank plugin specified by Slurm, but this path is set well in Slurm, it don't seem to recognize it. As an alternative, create a plugstack.conf file that explicitly defines the Spank Plugin library in the slurm config directory and specify the library path of spank_pyxis.so.

_Install Guide in Github  ← have a problem_
```
# ln -s /usr/local/share/pyxis/pyxis.conf /etc/slurm/plugstack.conf.d/pyxis.conf
# cat /usr/local/share/pyxis/pyxis.conf
required /usr/local/lib/slurm/spank_pyxis.so
```

_We changed install guide ← works well_
```
Master node
# vi /etc/slurm/plugstack.conf
required /usr/local/lib/slurm/spank_pyxis.so
# systemctl restart slurmctld && systemctl status slurmctld
Worker Nodes
# for i in {1..2}; do ssh node$i "mkdir /usr/local/lib/slurm"; done
# for i in {1..2}; do scp /usr/local/lib/slurm/spank_pyxis.so
node$i:/usr/local/lib/slurm/; done
# for i in {1..2}; do scp /etc/slurm/plugstack.conf node$i:/etc/slurm/; done
# for i in {1..4}; do ssh node$i "systemctl restart slurmd && systemctl status slurmd";
done

```

```
$ cat /etc/enroot/enroot.conf 
#ENROOT_LIBRARY_PATH        /usr/lib/enroot
#ENROOT_SYSCONF_PATH        /etc/enroot
ENROOT_RUNTIME_PATH        /tmp/enroot/user-$(id -u)
#ENROOT_CONFIG_PATH         ${XDG_CONFIG_HOME}/enroot
#ENROOT_CACHE_PATH          ${XDG_CACHE_HOME}/enroot
ENROOT_DATA_PATH           /tmp/enroot-data/user-$(id -u)
#ENROOT_TEMP_PATH           ${TMPDIR:-/tmp}

```
Had to change the PATH of ENROOT from /run to /tmp , otherwise it fails with 
slurmstepd: error: pyxis: mkdir: cannot create directory ‘/run/enroot’: Permission denied

**Comment by flx42** [comment] 2021-02-24 19:18
Hello,

1. Can we get the output of `cat /proc/cmdline`?

2. Regarding the standalone enroot test, was it ran as root or as a regular non-privileged user?

**Comment by pvaldria** [comment] 2021-02-24 19:42
There is 1 bastion/head node running slurm controller:   hostname: vocal-drake-bastion
There are 2 Baremetal GPU nodes with 8xA100 GPUs :  
**hostnames:**

1. inst-zv2gp-vocal-drake
2. inst-foysz-vocal-drake


```
[opc@inst-zv2gp-vocal-drake ~]$ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.4.17-2036.100.6.1.el7uek.x86_64 root=UUID=a46bac1b-7608-4d7c-b8c6-a3abca37be9f ro crashkernel=auto LANG=en_US.UTF-8 console=tty0 console=ttyS0,9600 rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 rd.iscsi.bypass=1 rd.net.timeout.carrier=5 rd.net.timeout.dhcp=10 netroot=iscsi:169.254.0.2:::1:iqn.2015-02.oracle.boot:uefi iscsi_param=node.session.timeo.replacement_timeout=6000 net.ifnames=1 nvme_core.shutdown_timeout=10 ipmi_si.tryacpi=0 ipmi_si.trydmi=0 ipmi_si.trydefaults=0 libiscsi.debug_libiscsi_eh=1 loglevel=4 ip=dhcp nouveau.modeset=0 rd.driver.blacklist=nouveau namespace.unpriv_enable=1 user_namespace.enable=1

```

```
[opc@inst-foysz-vocal-drake ~]$ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.4.17-2036.100.6.1.el7uek.x86_64 root=UUID=a46bac1b-7608-4d7c-b8c6-a3abca37be9f ro crashkernel=auto LANG=en_US.UTF-8 console=tty0 console=ttyS0,9600 rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 rd.iscsi.bypass=1 rd.net.timeout.carrier=5 rd.net.timeout.dhcp=10 netroot=iscsi:169.254.0.2:::1:iqn.2015-02.oracle.boot:uefi iscsi_param=node.session.timeo.replacement_timeout=6000 net.ifnames=1 nvme_core.shutdown_timeout=10 ipmi_si.tryacpi=0 ipmi_si.trydmi=0 ipmi_si.trydefaults=0 libiscsi.debug_libiscsi_eh=1 loglevel=4 ip=dhcp nouveau.modeset=0 rd.driver.blacklist=nouveau namespace.unpriv_enable=1 user_namespace.enable=1

```

**Bastion/Slurm Controller**
```
[opc@vocal-drake-bastion ~]$ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-4.14.35-1902.302.2.el7uek.x86_64 root=UUID=8082e99e-d42b-43df-88b5-f3b194271657 ro crashkernel=auto LANG=en_US.UTF-8 console=tty0 console=ttyS0,9600 rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 rd.iscsi.bypass=1 netroot=iscsi:169.254.0.2:::1:iqn.2015-02.oracle.boot:uefi iscsi_param=node.session.timeo.replacement_timeout=6000 net.ifnames=1 nvme_core.shutdown_timeout=10 ipmi_si.tryacpi=0 ipmi_si.trydmi=0 ipmi_si.trydefaults=0 libiscsi.debug_libiscsi_eh=1 loglevel=4
[opc@vocal-drake-bastion ~]$
```

**Comment by pvaldria** [comment] 2021-02-24 20:01
Regarding the standalone enroot test, was it ran as root or as a regular non-privileged user?

**Response:**   it was ran as “root” user and  “opc” user and “opc” has sudo privileges.

**Comment by pvaldria** [comment] 2021-02-24 20:13
I created a non-priviledge user on both GPU nodes and "standalone enroot test"  works on 1 node and fails on other, details below.  

**Node1:** 
```
[opc@inst-foysz-vocal-drake ~]$ sudo adduser nonprivuser
[opc@inst-foysz-vocal-drake ~]$ sudo su nonprivuser -l
[nonprivuser@inst-foysz-vocal-drake ~]$ pwd
/home/nonprivuser
[nonprivuser@inst-foysz-vocal-drake ~]$ enroot import docker://ubuntu
mkdir: cannot create directory ‘/tmp/enroot-data’: Permission denied
mkdir: cannot create directory ‘/tmp/enroot’: Permission denied
[nonprivuser@inst-foysz-vocal-drake ~]$

```

**Node2:**
```
[opc@inst-zv2gp-vocal-drake ~]$ sudo adduser nonprivuser2
[opc@inst-zv2gp-vocal-drake ~]$ sudo su nonprivuser2 -l
[nonprivuser2@inst-zv2gp-vocal-drake ~]$ pwd
/home/nonprivuser2
[nonprivuser2@inst-zv2gp-vocal-drake ~]$ enroot import docker://ubuntu
[INFO] Querying registry for permission grant
[INFO] Authenticating with user: <anonymous>
[INFO] Authentication succeeded
[INFO] Fetching image manifest list
[INFO] Fetching image manifest
[INFO] Downloading 4 missing layers...

100% 4:0=0s 83ee3a23efb7c75849515a6d46551c608b255d8402a4d3753752b88e0dc188fa

[INFO] Extracting image layers...

100% 3:0=0s 83ee3a23efb7c75849515a6d46551c608b255d8402a4d3753752b88e0dc188fa

[INFO] Converting whiteouts...

100% 3:0=0s 83ee3a23efb7c75849515a6d46551c608b255d8402a4d3753752b88e0dc188fa

[INFO] Creating squashfs filesystem...

Parallel mksquashfs: Using 128 processors
Creating 4.0 filesystem on /home/nonprivuser2/ubuntu.sqsh, block size 131072.
[=========================================================================================================================================================================================/] 2761/2761 100%

Exportable Squashfs 4.0 filesystem, lzo compressed, data block size 131072
	uncompressed data, compressed metadata, compressed fragments, compressed xattrs
	duplicates are removed
Filesystem size 51819.69 Kbytes (50.61 Mbytes)
	72.52% of uncompressed filesystem size (71452.34 Kbytes)
Inode table size 44507 bytes (43.46 Kbytes)
	25.76% of uncompressed inode table size (172778 bytes)
Directory table size 33525 bytes (32.74 Kbytes)
	51.60% of uncompressed directory table size (64974 bytes)
Xattr table size 53 bytes (0.05 Kbytes)
	100.00% of uncompressed xattr table size (53 bytes)
Number of duplicate files found 110
Number of inodes 3263
Number of files 2501
Number of fragments 286
Number of symbolic links  184
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 578
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
[nonprivuser2@inst-zv2gp-vocal-drake ~]$ enroot create ubuntu.sqsh
[INFO] Extracting squashfs filesystem...

Parallel unsquashfs: Using 128 processors
2689 inodes (2945 blocks) to write

[=========================================================================================================================================================================================|] 2945/2945 100%

created 2501 files
created 578 directories
created 184 symlinks
created 0 devices
created 0 fifos
[nonprivuser2@inst-zv2gp-vocal-drake ~]$ enroot start ubuntu
nonprivuser2@inst-zv2gp-vocal-drake:/$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
nonprivuser2@inst-zv2gp-vocal-drake:/$
```

**Comment by 3XX0** [comment] 2021-02-24 20:15
This looks like a different error, you don't have permission to create the enroot config directories.

Did you make sure that the enroot test was done on the same node that slurm selected for your job?
Can you try an explicit test like:
```
salloc-w inst-zv2gp-vocal-drake
srun ./enroot-check_3.2.0_x86_64.run
srun --container-image ubuntu true
```

**Comment by pvaldria** [comment] 2021-02-24 20:26
Output: 

```
[opc@inst-zv2gp-vocal-drake ~]$ salloc -w inst-zv2gp-vocal-drake
salloc: Granted job allocation 38
[opc@inst-zv2gp-vocal-drake ~]$ srun /tmp/enroot-check_3.2.0_x86_64.run
enroot-nsenter: failed to create user namespace: Permission denied
srun: error: inst-zv2gp-vocal-drake: task 0: Exited with exit code 1
[opc@inst-zv2gp-vocal-drake ~]$
```

**Comment by pvaldria** [comment] 2021-02-24 20:28
or do I need to run the above command as a privilege (without sudo)  user ?

**Comment by 3XX0** [comment] 2021-02-24 20:29
No you shouldn't need to be privileged.
Does `/tmp/enroot-check_3.2.0_x86_64.run` itself work on `inst-zv2gp-vocal-drake` without slurm?

**Comment by pvaldria** [comment] 2021-02-24 20:31
```
[opc@inst-zv2gp-vocal-drake ~]$ /tmp/enroot-check_3.2.0_x86_64.run
Extracting [####################] 100%
Bundle ran successfully!
```


```
[opc@inst-zv2gp-vocal-drake ~]$ sudo su nonprivuser2 -l
Last login: Wed Feb 24 20:09:46 GMT 2021 on pts/0
[nonprivuser2@inst-zv2gp-vocal-drake ~]$ /tmp/enroot-check_3.2.0_x86_64.run
Extracting [####################] 100%
Bundle ran successfully!
[nonprivuser2@inst-zv2gp-vocal-drake ~]$

```

**Comment by pvaldria** [comment] 2021-02-24 20:40
I have sent the nvidia bug reports from the 2 nodes to Ty Mckercher via email to share with you.

**Comment by 3XX0** [comment] 2021-02-24 20:49
It looks like your SLURM is doing something that prevent enroot from running somehow.
Can you try disabling selinux temporarily if you have it setup, see if it fixes the issue:
```
srun -w inst-zv2gp-vocal-drake /tmp/enroot-check_3.2.0_x86_64.run

# compare with

srun -w inst-zv2gp-vocal-drake sh -c 'sudo setenforce 0;  /tmp/enroot-check_3.2.0_x86_64.run; sudo setenforce 1'
```

**Comment by pvaldria** [comment] 2021-02-24 20:53
Get the same error on other node (inst-foysz-vocal-drake) also. 
```

[opc@inst-foysz-vocal-drake ~]$ salloc -w inst-foysz-vocal-drake
salloc: Granted job allocation 40
[opc@inst-foysz-vocal-drake ~]$ srun /tmp/enroot-check_3.2.0_x86_64.run
enroot-nsenter: failed to create user namespace: Permission denied
srun: error: inst-foysz-vocal-drake: task 0: Exited with exit code 1
[opc@inst-foysz-vocal-drake ~]$
```

But enroot_check*run works fine with opc as well as nonprivuser user. 


```
[opc@inst-foysz-vocal-drake ~]$ /tmp/enroot-check_3.2.0_x86_64.run
Extracting [####################] 100%
Bundle ran successfully!
[opc@inst-foysz-vocal-drake ~]$
```


```
sudo su nonprivuser -l
Last login: Wed Feb 24 20:06:47 GMT 2021 on pts/0
[nonprivuser@inst-foysz-vocal-drake ~]$ /tmp/enroot-check_3.2.0_x86_64.run
Extracting [####################] 100%
Bundle ran successfully!
[nonprivuser@inst-foysz-vocal-drake ~]$

```

Not sure, if the below is relevant to this investigation, but thought i still share 
As  nonprivuser user.
```
[nonprivuser@inst-foysz-vocal-drake ~]$ salloc -w inst-foysz-vocal-drake
salloc: Granted job allocation 39
[nonprivuser@inst-foysz-vocal-drake ~]$ srun /tmp/enroot-check_3.2.0_x86_64.run
srun: error: Unable to create step for job 39: Error generating job credential
[nonprivuser@inst-foysz-vocal-drake ~]$

```

**Comment by pvaldria** [comment] 2021-02-24 20:55
```
[opc@inst-zv2gp-vocal-drake ~]$ srun -w inst-zv2gp-vocal-drake /tmp/enroot-check_3.2.0_x86_64.run
enroot-nsenter: failed to create user namespace: Permission denied
srun: error: inst-zv2gp-vocal-drake: task 0: Exited with exit code 1

```


```
[opc@inst-zv2gp-vocal-drake ~]$ srun -w inst-zv2gp-vocal-drake sh -c 'sudo setenforce 0;  /tmp/enroot-check_3.2.0_x86_64.run; sudo setenforce 1'
Bundle ran successfully!
[opc@inst-zv2gp-vocal-drake ~]$


```

**Comment by pvaldria** [comment] 2021-02-24 20:58
We normally disable SELinux as part of the install process.   Could it be that when we ran grubby to add enroot required kernel parameters,  it enables SELinux again ?

**Comment by tym1062** [comment] 2021-02-24 21:08
> I have sent the nvidia bug reports from the 2 nodes to Ty Mckercher via email to share with you.

Thanks - i have shared these bug logs with the NVIDIA team.

**Comment by 3XX0** [comment] 2021-02-24 21:14
> We normally disable SELinux as part of the install process. Could it be that when we ran grubby to add enroot required kernel parameters, it enables SELinux again ?

Could be yeah, also you probably have a different profile applied through the SLURM binaries, otherwise it wouldn't work normally

**Comment by pvaldria** [comment] 2021-02-24 21:21
I am disabling SELinux and rebooting the nodes.

**Comment by pvaldria** [comment] 2021-02-24 21:54
**Node1:** 
```
[opc@vocal-drake-bastion ~]$ ssh 172.16.4.2
[opc@inst-zv2gp-vocal-drake ~]$ sudo chown -R opc:opc /tmp/enroot
[opc@inst-zv2gp-vocal-drake ~]$ sudo chown -R opc:opc /tmp/enroot-data
[opc@inst-zv2gp-vocal-drake ~]$ srun -w inst-zv2gp-vocal-drake --container-image=/nfs/cluster/pyxis_test/enroot_image/centos.sqsh grep PRETTY /etc/os-release
PRETTY_NAME="CentOS Linux 8"
[opc@inst-zv2gp-vocal-drake ~]$ exit
```

**Node2:** 
```
[opc@vocal-drake-bastion ~]$ ssh 172.16.4.3
Last login: Wed Feb 24 21:21:56 2021 from vocal-drake-bastion.public.cluster.oraclevcn.com
[opc@inst-foysz-vocal-drake ~]$ getenforce
Disabled
[opc@inst-foysz-vocal-drake ~]$ srun -w inst-foysz-vocal-drake --container-image=/nfs/cluster/pyxis_test/enroot_image/centos.sqsh grep PRETTY /etc/os-release
PRETTY_NAME="CentOS Linux 8"
[opc@inst-foysz-vocal-drake ~]$

```

**Comment by flx42** [comment] 2021-02-24 22:14
Nice! So now it seems to work. Is this an acceptable solution for this setup?

If not, you might want to review the Slurm and SELinux configurations on the system, as the problem is likely not specific to enroot, i.e. `srun unshare --user --map-root-user` will probably fail too (creating a user namespace outside of enroot).

**Comment by pvaldria** [comment] 2021-02-26 07:13
Thanks to Nvidia team,  Issue was resolved by disabling SELinux.    We can close this ticket.

**Closed** 2021-02-26 18:39 UTC
