### ISSUE TITLE
enroot-mount reports fail at specific directory.

### ISSUE THREAD

**Issue by coldbloodx** [NVIDIA/enroot#36] opened 2020-09-06 07:04 UTC
enroot reports enroot-mount fail when cwd is some specific directory.

see below example:
yingbai@lsf1x125[yingbai]:$ mycommand /bin/bash --> pwd is /opt/yingbai
...
final cli:
```
/usr/bin/enroot start --mount /scratch/lsf_addon/lcui/lsf1011:/scratch/lsf_addon/lcui/lsf1011 --mount /home/yingbai:/home/yingbai --mount /tmp:/tmp --mount /opt/yingbai:/opt/yingbai --rw -m /scratch/lsf_addon/lcui/:/scratch/lsf_addon/lcui/ --mount /scratch/lsf_addon/lcui/passwd:/etc/passwd -m /scratch/lsf_addon/lcui/group:/etc/group -c /tmp/.lsf1011.job.conf.933 ubuntu /home/yingbai/.lsbatch/1599375571.933
enroot-mount: failed to mount: /opt/yingbai at /home/yingbai/.local/share/enroot/ubuntu/opt/yingbai: No such file or directory
```
**^^^^^^fail!!! this is not always reproduce, I cannot figure out why, any inputs?**

yingbai@lsf1x125[~]:$ mycommand /bin/bash. --> pwd is /home/yingbai

final cli:
```
/usr/bin/enroot start --mount /tmp:/tmp --mount /home/yingbai:/home/yingbai --mount /home/yingbai/:/home/yingbai/ --mount /scratch/lsf_addon/lcui/lsf1011:/scratch/lsf_addon/lcui/lsf1011 --rw -m /scratch/lsf_addon/lcui/:/scratch/lsf_addon/lcui/ --mount /scratch/lsf_addon/lcui/passwd:/etc/passwd -m /scratch/lsf_addon/lcui/group:/etc/group -c /tmp/.lsf1011.job.conf.934 ubuntu /home/yingbai/.lsbatch/1599375579.934
groups: cannot find name for group ID 100001
yingbai@lsf1x125:/$
```
--> success!!!

**Comment by 3XX0** [comment] 2020-09-08 17:54
Anything different with your `/opt/yingbai` directory? Is it a network share or something?
Maybe check that `/opt/yingbai` exists both inside and outside the container and has been created correctly inside.
It looks like `mount` fails with `ENOENT` so something must be missing

**Comment by 3XX0** [comment] 2020-10-21 21:51
Closing, feel free to reopen if you can reproduce the issue

**Closed by 3XX0** 2020-10-21 21:51 UTC
