### ISSUE TITLE
Issue with 50-slurm-pytorch.sh

### ISSUE THREAD

**Issue by vfdev-5** [NVIDIA/enroot#93] opened 2021-09-21 10:05 UTC
For certain instances on AWS we can have 
```
srun: jobid 41: nodes(2):`cpu-compute-spot-dy-c5large-[1-2]', cpu counts: 1(x2)
```
or `echo $SLURM_STEP_TASKS_PER_NODE` > `1(x2)`
which may fail in the hook:
```
/usr/local/etc/enroot/hooks.d/50-slurm-pytorch.sh: line 39: [: 1(x2): integer expression expected
```

**Comment by flx42** [comment] 2021-09-21 15:53
Moved to enroot, thanks for the report @vfdev-5, what is your Slurm version by the way?

**Comment by 3XX0** [comment] 2021-09-21 21:30
Do you mind sharing how you launched the job?

**Comment by vfdev-5** [comment] 2021-09-22 11:35
Sure, something like that:
```
NVIDIA_VISIBLE_DEVICES="" srun --partition=cpu-compute-spot --container-name=ignite-vision --container-image=/shared/enroot_data/pytorchignite+vision+latest.sqsh bash -c 'echo "Enroot pytorch hook applied: $WORLD_SIZE:$RANK:$LOCAL_RANK:$MASTER_ADDR:$MASTER_PORT"'
```

**Comment by flx42** [comment] 2021-09-22 16:40
How many nodes and how many tasks per node is your slurm job using?

**Comment by vfdev-5** [comment] 2021-09-22 16:41
It is 1 node and 1 task per node. Default values

**Comment by flx42** [comment] 2021-09-22 18:42
Thanks, I can reproduce the issue, but it isn't causing the hook to fail, it just causes `OMP_NUM_THREADS` to not be set as it should be.

Is the container start failing because of this in your case?

**Comment by flx42** [comment] 2021-09-22 21:55
Hopefully fixed with https://github.com/NVIDIA/enroot/commit/46725c62267110745053b808f12a6f878ce208d3, let us know if that's not the case

**Closed** 2021-09-22 21:55 UTC

**Comment by vfdev-5** [comment] 2021-09-23 13:43
> Is the container start failing because of this in your case?

No, it does fail to start but env vars are not completely defined. I had also somehow MASTER_ADDR as not defined...
